#!/bin/bash

#AM-368 Setup USB Rules for communication requirements

# root is required, but you are using apt install so you must be root already
echo "SUBSYSTEM==\"usb\", ATTRS{idVendor}==\"2ca3\", MODE=\"0666\"" > /etc/udev/rules.d/DJIDevice.rules